version: "3.9"
services:
  database:
    image: postgres:15
    restart: always
    # Uncomment the next line to help debug database functions by logging the queries the DB receives.
    # command: postgres -c log_statement=all -c log_destination=stderr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
